function createfigure2(X1, YMatrix1)
%CREATEFIGURE2(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-May-2017 16:50:03

% Create figure
figure1 = figure('PaperType','a4letter',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Times New Roman');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[1 0.200000002980232 0.400000005960464],...
    'DisplayName','M_ñ_ì = 0 Í*ì');
set(plot1(2),'LineStyle','-.',...
    'Color',[0.200000002980232 0.600000023841858 1],...
    'DisplayName','M_ñ_ì = 20 Í*ì');
set(plot1(3),'Color',[1 1 0],'DisplayName','M_ñ_ì = 50 Í*ì');
set(plot1(4),'LineStyle','--','Color',[0 1 0],...
    'DisplayName','M_ñ_ì = 92 Í*ì');

% Create xlabel
xlabel('t, c','FontSize',12,'FontName','Times New Roman');

% Create ylabel
ylabel('I, A','FontSize',12,'FontName','Times New Roman');

% Create legend
legend(axes1,'show');

