function createfigure2(X1, YMatrix1)
%CREATEFIGURE2(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 30-May-2017 21:56:18

% Create figure
figure1 = figure('PaperType','a4letter',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20,'FontName','Times New Roman');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[1 0.200000002980232 0.400000005960464],...
    'DisplayName','m=0.125 Í„');
set(plot1(2),'LineStyle','-.',...
    'Color',[0.200000002980232 0.600000023841858 1],...
    'DisplayName','m=0.250 Í„');
set(plot1(3),'Color',[1 1 0],'DisplayName','m=0.375 Í„');


% Create xlabel
xlabel('t, c','FontSize',20,'FontName','Times New Roman');

% Create ylabel
ylabel('F, H','FontSize',20,'FontName','Times New Roman');
% Create legend
legend(axes1,'show');

