function createfigure2(simout1, YMatrix1)
%CREATEFIGURE2(SIMOUT1, YMATRIX1)
%  SIMOUT1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-May-2017 18:07:56

% Create figure
figure1 = figure('Color',...
    [0.972549021244049 0.972549021244049 0.972549021244049]);

% Create axes
axes1 = axes('Parent',figure1,'YGrid','on','XGrid','on','FontSize',20,...
    'FontName','Times New Roman');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(simout1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'LineStyle','--',...
    'Color',[0.0784313753247261 0.168627455830574 0.549019634723663],...
    'DisplayName','\omega_п_о_л_н');
set(plot1(2),'Color',[1 0 1],'DisplayName','\alpha_п_о_л_н');
set(plot1(3),'Color',[0 1 0],'DisplayName','\omega_у_п_р');
set(plot1(4),'LineStyle','--','Color',[1 0 0],'DisplayName','\alpha_у_п_р');

% Create xlabel
xlabel(' t, c','Interpreter','none','FontSize',20,...
    'FontName','Times New Roman');

% Create ylabel
ylabel('\omega, рад/с','FontSize',20,'FontName','Times New Roman');

% Create title
title('','Interpreter','none');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.701388888888888 0.168929110105581 0.181547619047619 0.441930618401207]);

