function createfigure2(X1, Y1)
%CREATEFIGURE2(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 30-May-2017 16:21:42

% Create figure
figure1 = figure('PaperType','a4letter',...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',20,'FontName','Times New Roman');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0.200000002980232 0.600000023841858 1],...
    'DisplayName','getcolumn(f_1(t)=1.5, f_2(t)=0,1)');

% Create xlabel
xlabel({'t, c'},'FontSize',20,'FontName','Times New Roman');

% Create ylabel
ylabel({'X, ì'},'FontSize',20,'FontName','Times New Roman');

