function createfigure2(X1, Y1)
%CREATEFIGURE2(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 27-May-2017 18:05:33

% Create figure
figure1 = figure('PaperType','a4letter',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391]);

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12,'FontName','Times New Roman');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'LineWidth',2,'Color',[0.200000002980232 0.600000023841858 1],...
    'DisplayName','f_1(t)=1.5, f_2(t)=0');

% Create xlabel
xlabel('t, c','FontSize',12,'FontName','Times New Roman');

% Create ylabel
ylabel('y(t)','FontSize',12,'FontName','Times New Roman');

