function createlegend(axes1)
%CREATELEGEND(AXES1)
%  AXES1:  legend axes

%  Auto-generated by MATLAB on 01-Jun-2017 23:17:25

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'LineWidth',2);
set(legend2,'LineWidth',2);


