function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 22-May-2017 16:48:37

% Create figure
figure1 = figure('PaperType','a4letter',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'Color',[0.941176474094391 0.941176474094391 0.941176474094391]);

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);
set(plot1(1),'Color',[0.200000002980232 0.600000023841858 1],...
    'DisplayName','k=1');
set(plot1(2),'Color',[0 1 0],'DisplayName','k=5');
set(plot1(3),'Color',[1 0.200000002980232 0.400000005960464],...
    'DisplayName','k=10');

% Create xlabel
xlabel('t, ñ','Interpreter','none');

% Create ylabel
ylabel('e(t)','Interpreter','none');

% Create legend
legend(axes1,'show');

